// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLtv8f6AaugaPBQv6k6U3ySRDLHyTuAh4',
    appId: '1:163650984826:web:b33b3273756be9e15814c3',
    messagingSenderId: '163650984826',
    projectId: 'my-voca-6ffe6',
    authDomain: 'my-voca-6ffe6.firebaseapp.com',
    databaseURL: 'https://my-voca-6ffe6-default-rtdb.firebaseio.com',
    storageBucket: 'my-voca-6ffe6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApgD9ML-d3g1PsVOvfsgfNOwecxtxUajs',
    appId: '1:163650984826:android:87ec21ef25502d105814c3',
    messagingSenderId: '163650984826',
    projectId: 'my-voca-6ffe6',
    databaseURL: 'https://my-voca-6ffe6-default-rtdb.firebaseio.com',
    storageBucket: 'my-voca-6ffe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjyqVryiWgq13QkzULKIknBiwZ3CLuzmU',
    appId: '1:163650984826:ios:f430e3c568923a135814c3',
    messagingSenderId: '163650984826',
    projectId: 'my-voca-6ffe6',
    databaseURL: 'https://my-voca-6ffe6-default-rtdb.firebaseio.com',
    storageBucket: 'my-voca-6ffe6.appspot.com',
    iosBundleId: 'com.example.myVoca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjyqVryiWgq13QkzULKIknBiwZ3CLuzmU',
    appId: '1:163650984826:ios:f430e3c568923a135814c3',
    messagingSenderId: '163650984826',
    projectId: 'my-voca-6ffe6',
    databaseURL: 'https://my-voca-6ffe6-default-rtdb.firebaseio.com',
    storageBucket: 'my-voca-6ffe6.appspot.com',
    iosBundleId: 'com.example.myVoca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLtv8f6AaugaPBQv6k6U3ySRDLHyTuAh4',
    appId: '1:163650984826:web:baf26e23f2a13cde5814c3',
    messagingSenderId: '163650984826',
    projectId: 'my-voca-6ffe6',
    authDomain: 'my-voca-6ffe6.firebaseapp.com',
    databaseURL: 'https://my-voca-6ffe6-default-rtdb.firebaseio.com',
    storageBucket: 'my-voca-6ffe6.appspot.com',
  );
}
